"""remove zip code

Revision ID: fa0d61e412e9
Revises: fcf26f9c9589
Create Date: 2026-01-24 10:37:32.042238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0d61e412e9'
down_revision = 'fcf26f9c9589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address_zip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_zip', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
