"""split address fields

Revision ID: fcf26f9c9589
Revises: 3f6021051f5d
Create Date: 2026-01-24 10:35:39.008078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf26f9c9589'
down_revision = '3f6021051f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_street', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address_zip', sa.String(length=20), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('address_zip')
        batch_op.drop_column('address_state')
        batch_op.drop_column('address_city')
        batch_op.drop_column('address_street')

    # ### end Alembic commands ###
